common: &common
  adapter: postgresql
  username: postgres
  password:
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

development:
  <<: *common
  database: flickr_dev
production:
  <<: *common
  database: flickr_pro
test:
  <<: *common
  database: flickr_test